### ISSUE TITLE
Learn from Dropbox's bug

### ISSUE THREAD

**Issue by humphd** [mozilla/makedrive#167]
See https://medium.com/@jan.curn/how-bug-in-dropbox-permanently-deleted-my-8000-photos-cb7dcf13647b and let's extract lessons we can learn and file some bugs.

**Comment by gideonthomas** [comment]
This needs to be dealt with in https://github.com/mozilla/makedrive/issues/368 but as far as I know, data loss is unlikely to occur. Basically, an 'unsync' command would first be sent to the server and it will ignore all requests to sync that file/directory, only then should a deletion occur (purely based on how MakeDrive is used).

Closing this as it does not really have any implications on https://github.com/mozilla/makedrive/issues/368
