### ISSUE TITLE
Consider adding stable client identifiers to sync data

### ISSUE THREAD

**Issue by humphd** [mozilla/makedrive#374]
In #372 we ran into an issue where changes by the same client over time were being lost when the server asked for the client to downstream old versions of a file.  One way to fix this would have been for the client and server to know about each other, and see that a single client had new changes to data it already synced in the past (i.e., when there is only 1 client in the mix, we can basically take whatever changes it has, since it's a pure mirror).

Dropbox solves this by using installed clients with unique identifiers.  On the web we don't have a way to uniquely identify a client between connections.  However, we can get around this by "installing" a unique client ID into the filesystem, which does survive sessions.  We could generate a client UUID and write it into an xattrib on the root node of the filesystem, for example.  Every sync step could then include both the username, the session token, and the client's stable UUID.  This would allow us to decide how to deal with sync data and versions based on what we know about who made previous syncs.

**Comment by gideonthomas** [comment]
I think the versioning part is fixed by storing the checksum of the last synced version of the file and comparing that with what needs to be downstreamed. We have already implemented this.

Is there any other reason that we would need client IDs for?

**Comment by humphd** [comment]
It's unclear to me whether or not this is a useful thing to do or not.  I think we should close this and open if we find we want it later.
