### ISSUE TITLE
Safely allow server-side creation of new files in order to overcome origin issues

### ISSUE THREAD

**Issue by humphd** [mozilla/makedrive#417]
Imagine I want to put http://some-other-origin.com/image.png into my filesystem.  I have two options:
- download it in the browser (XHR), get the raw bytes, `fs.writeFile()`, and sync to the server
- download it on the server (request), get the raw bytes, `fs.writeFile()`, send an `OUT_OF_DATE` message to the client(s), and do downstream syncs to give them the file.

The problem with the first method is that we can't get the raw bytes for a file we XHR unless it's same-origin.  In order to make it possible, we'd have to proxy the file from our MakeDrive origin (e.g., XHR https://makedrive.webmaker.org/download?url=http://some-other-origin.com/image.png).  This is possible, but also kind of sucks.

Another option is to do what I've outlined above in option 2, specifically, we somehow tell the MakeDrive server to download this file and get its raw bytes (no origin restrictions on server-side).  The tricky part is simulating having the server be another client for this user, and safely writing this new file to the user's filesystem without causing a conflict.

This will help with #402, and the case that we want to "download" an arbitrary URL into our filesystem.

**Comment by gideonthomas** [comment]
@humphd would we want to implement this only to avoid cross origin issues?

**Comment by humphd** [comment]
Correct.  I think it's worth exploring, but it's not a P1 I don't think.  Users are going to want to stuff things into their filesystem that they find on the web.  We need to support that somehow, given origin policy.
