### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by DiegoBM** [mozilla/makedrive#486]
Sorry I didn't know where to ask or check for status. I reckon this is a very interesting project but it has not received updates in years and I can't find any modern sign of it being alive, so if anyone could tell us about the status of MakeDrive whatever it is (maybe it was absorbed by another Mozilla project?), I'd be thankful

**Comment by gideonthomas** [comment]
Hi @DiegoBM, thank you for showing interest in this project. Unfortunately, this project has been deprecated (needs a README update to show that) as we've decided to move in a different strategic direction. As such, we have no active maintainers of this project at Mozilla. That being said, I would encourage you to fork the project and take it over if you are interested.
